### PR TITLE
Created a configuration file.

### PR DESCRIPTION
**Pull request by fuzzyTew**
Moved initialState into the configuration file.

This file lives outside js/ to help distinguish code modules from data.

This PR is kind of a "proposition" -- this is where I would start to move things; what do you think?

### CODE REVIEW

**Comment by rdbartlett** [comment]
Looks good to me! Thanks :)

**Comment by rdbartlett** [comment]
Whoops I merged this too hastily. Reverted now. Did I mention my rudimentary codings skills? 😆

**Comment by xloem** [comment]
Hey =)  Is the kind of change you'd like?  Or would you rather configuration data stay in /js/? (sorry, I am fuzzyTew)

**Comment by rdbartlett** [comment]
Let's figure it out on git-ssb! http://localhost:7718/%25grhxZmqVDTloK1lrUYOxzmtUlVXECD5SEdQ9tZzhLZE%3D.sha256/

**Pull request merged**
